name: Compile XA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd xa ; make
    - uses: actions/upload-artifact@v3
      with:
        name: xa
        path: xa/xa
